# Generated by Django 4.0.4 on 2022-05-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to='media/profile_photoes'),
        ),
    ]
