# Generated by Django 4.0.4 on 2022-05-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_age_profile_anime_love_level_profile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeplaylist',
            name='date_aired',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='animeplaylist',
            name='duration_episode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='animeplaylist',
            name='playlist_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='animeplaylist',
            name='quality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='animeplaylist',
            name='rating',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='animeplaylist',
            name='scores',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='animeplaylist',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='animeplaylist',
            name='studio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
