# Generated by Django 4.0.4 on 2022-05-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_animeplaylist_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeplaylist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animeplaylist',
            name='quality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
