# Generated by Django 4.0.4 on 2022-05-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_useranimeplaylist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='animeplaylist',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='core.comment'),
        ),
    ]
