# Generated by Django 4.0.4 on 2022-05-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_animeplaylist_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='preview_photo',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
